services:
  terraform:
    image: hashicorp/terraform
    working_dir: /w
    volumes:
      - ./tf:/w
    command:
      - plan
  statesaver:
    build:
      context: .
      dockerfile: Dockerfile.build
    command:
      - /statesaver
      - server
      - --verbose
    volumes:
      - ./data:/data
    environment:
      STSV_DATADIR: /data
      TZ: Asia/Tokyo
